#
# This config contains behaviour data: Thread allocation, allowed fields for lookup, limits for arguments etc.
#
# The behaviour config is normally controlled by developers and is part of the code repository.
# Sensitive information such as machine names and user/passwords should not be part of this config.
#
# It will be automatically merged with the environment config when accessed through the
# application config system.
#
#

alma:

  apikey: SHOULD SET IN librarylending-environment.yaml or librarylending-local.yaml


  # The Alma URL. This should never change, you control which alma instance you use by the key, not the url
  url: https://api-eu.hosted.exlibrisgroup.com/almaws/v1/

  lang: da

  #This parameter is nessesary when retrieving Resource Sharing Requests. It does not really matter what it it,
  # but it NEEDS to be the code of any Partner. 800010 is the code of KGL Bib, and not likely to change.
  partner_code: 800010

  #How many requests per call, max 100
  batch_size: 100

  #The alma client will retry this number of times before giving up.
  # If set to negative value, the client will retry forever
  # if set to 0, no retries will be attempted.
  max_retries: 3
  # Not that HTTP 429 (Rate Limit) from ALMA will NOT be affected by this value, and these will always be retried forever

  #cache alma responses for this duration. Milliseconds
  # Cache for 1 minute, to handle repeated calls
  cache_timeout: 60000

  #Timeouts in milliseconds
  connect_timeout: 30000
  read_timeout: 30000

  # Sleep durations when retrying or receiving a response 429 from alma (rate_limit)
  rate_limit:
    #When we retry we back off for at least min_sleep_millis
    min_sleep_millis: 2000
    #to avoid the rush when a lot of threads back off and then try again at the same time, we introduce a random element into
    # the back off time. sleep_variation_millis multiplied with a randon number [0-1] will be added to the sleep time to combat this effect
    sleep_variation_millis: 3000

pdfService:
  #  Where original PDFs are read from
  PDFsource:
    - "/data1/e-mat/dod"
  #  Where generated PDFs are stored
  PDFTempFolder: "temp/"
  # If copyrighted PDF is older than this age, request ALMA data and create it again
  # This ensures that updates to ALMA will tage effect (after a while)
  # Note that if this age is SHORTER than the alma.cache_timeout, the cached ALMA record
  # will be used, which defeats the purpose....
  maxAgeOfTempPdfsInMinutes:
    value: 5
    unit: MINUTES
    # unit can be one of NANOS, MICROS, MILLIS, SECONDS, MINUTES, HOURS, HALF_DAYS

  # When inserting new front page, we search for old frontpages to remove
  # If a page contains any of these strings (case insensitive), it is regarded
  # as a frontpage and removed
  # As soon as we find a page that is NOT a frontpage, we stop the search. So there
  # should be no problem with removing pages deep in document
  oldHeaderStrings:
    - "det kongelige bibliotek"
    - "det kgl. bibliotek"
    - "digitaliseret af"

  # How long must pass since publication for at work to be outside copyright
  TimeSincePublicationToBeOutsideCopyright:
    value: 140
    unit: YEARS

  # The frontpage to use
  frontpage:
    FOPfile: /home/pdf/services/conf/frontpage.xsl

  # Details of the footer to insert, if the document is under copyright
  copyrightFooter:
    Text: "Manuskriptkopien må ikke anvendes til opførelse og må ikke videre distribueres."
    Fontsize: 14
    # See https://www.rapidtables.com/web/color/html-color-codes.html for possible values
    BackgroundColor: '#FFFF00'

