package dk.kb.pdfservice.alma;

public enum DocumentType {

    DOD_USER_REQUEST, DANISH_MONOGRAPHIES, //CASE A
    
    PROJECTDIGITISATIONS_OUTSIDE_COPYRIGHT, TEATERMANUSCRIPTS_OUTSIDE_COPYRIGHT, // CASE B
    
    TEATERMANUSCRIPTS_INSIDE_COPYRIGHT, // CASE C
    
    CC0_GRUNDTVIG //CASE D

}
