openapi: 3.0.2
info:
  version: "${project.version}"
  title: "${project.name}"
  description: |
    ${project.description}
  contact:
    email: "${user.name}@kb.dk"
  license:
    name: "${license.name}"
    url: "${license.url}"
servers:
  #  /api must match servlet-mapping in web.xml
  - url: "/${project.artifactId}/api"
    description: "Current server"
paths:
  /ping:
    get:
      tags:
        - "${project.name}"
      summary: Ping the server to check if the server is reachable.
      operationId: ping
      x-useGenericResponse: false # If enabled the method will return Response
      x-streamingOutput: false # If enabled the method will return StreamingOutput.
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Error
          content:
            text/plain:
              schema:
                type: string
  /getManuscript:
    get:
      tags:
        - "${project.name}"
      summary: 'Request a theater manuscript summary.'
      operationId: getManuscript
      x-streamingOutput: true # If enabled the method will return StreamingOutput.
      parameters:
        - name: barcode
          in: query
          description: Barcode for a theater manuscript
          required: true
          schema:
            type: string
            example: 130018972949
        - name: pdflink
          in: query
          description: pdfLink for a theater manuscript
          required: true
          schema:
            type: string
            example: string
      responses:
        '200':
          description: A pdf with attached page
          content:
            application/pdf:
              schema:
                type: string
                format: binary
  /getRawManuscript:
    get:
      tags:
        - "${project.name}"
      summary: 'Request a theater manuscript summary.'
      operationId: getRawManuscript
      parameters:
        - name: barcode
          in: query
          description: Barcode for a theater manuscript
          required: true
          schema:
            type: string
            example: 130018972949
      responses:
        '200':
          description: A pdf with attached page
          content:
            application/xml:
 #           text/xml:
              schema:
                type: string
  /getPdf:
    get:
      tags:
        - "${project.name}"
      summary: 'Request a Pdf file from link.'
      operationId: getPdf
      x-streamingOutput: true # If enabled the method will return StreamingOutput.
      parameters:
        - name: barcode
          in: query
          description: Barcode for a theater manuscript
          required: true
          schema:
            type: string
            example: 130018852943
        - name: pdflink2
          in: query
          description: Pdf for a theater manuscript
          required: true
          schema:
            type: string
            example: TS_DRAlaes-A552.pdf
      responses:
        '200':
          description: A pdf with attached page
          content:
            application/pdf:
              schema:
                type: string
                format: binary

components:
  schemas:
    HelloReply:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Greeting from the API
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
