openapi: 3.0.2
info:
  version: "${project.version}"
  title: "${project.name}"
  description: |
    ${project.description}
  contact:
    email: "${user.name}@kb.dk"
  license:
    name: "${license.name}"
    url: "${license.url}"
servers:
  #  /api must match servlet-mapping in web.xml
  - url: "/${project.artifactId}/api"
    description: "Current server"
paths:
  /getPdf/{pdfFile}:
    get:
      tags:
        - "${project.name}"
      summary: 'Request a Pdf file from link.'
      operationId: getPdf
      x-streamingOutput: true # If enabled the method will return StreamingOutput.
      parameters:
        - name: pdfFile
          in: path
          required: true
          schema:
            type: string
            example: 130018852943.pdf
      responses:
        '200':
          description: A pdf with attached page
          content:
            application/pdf:
              schema:
                type: string
                format: binary

components:
  schemas:
    HelloReply:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Greeting from the API
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
